[versions]
targetSdkVersion = "35"
minSdkVersion = "24"
javaVersion = "17"
agp = "8.9.1"
kotlin = "2.0.21"
kspPluginVersion = "2.0.21-1.0.27"
googleServicesVersion = "4.4.4"

coreKtx = "1.16.0"
espressoCore = "3.5.0"
lifecycleRuntimeKtx = "2.9.0"
activityCompose = "1.10.1"
composeBom = "2024.09.00"

koinVersion = "3.5.3"
retrofitVersion = "2.9.0"
navigationCompose = "2.8.0"
coil = "3.0.4"
roomVerison = "2.7.1"
kotlinxCoroutinesTestVersion = "1.10.2"
junitJupiterVersion = "5.11.0"

pahoClientVersion = "1.2.5"



[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

koin = {group = "io.insert-koin", name="koin-android", version.ref = "koinVersion"}
koin-compose = {group = "io.insert-koin", name="koin-androidx-compose", version.ref = "koinVersion"}

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

retrofit = {group = "com.squareup.retrofit2", name="retrofit", version.ref="retrofitVersion"}
retrofit-converter-moshi = {group = "com.squareup.retrofit2", name="converter-moshi", version.ref="retrofitVersion"}
retrofit-converter-gson = {group = "com.squareup.retrofit2", name="converter-gson", version.ref = "retrofitVersion"}
retrofit-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version = "1.0.0" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.6.3" }

coil-compose = {group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil"}
coil-network = {group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil"}

room-runtime = {group = "androidx.room", name = "room-runtime", version.ref="roomVerison"}
room-ksp = {group = "androidx.room", name = "room-compiler", version.ref="roomVerison"}

kotlinx-coroutines-test = {group = "org.jetbrains.kotlinx", name="kotlinx-coroutines-test", version.ref="kotlinxCoroutinesTestVersion"}
junit-jupiter-api = {group = "org.junit.jupiter", name="junit-jupiter-api", version.ref="junitJupiterVersion"}
junit-jupiter-engine = {module = "org.junit.jupiter:junit-jupiter-engine", version.ref="junitJupiterVersion"}

androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

paho-client = {group = "org.eclipse.paho", name ="org.eclipse.paho.client.mqttv3", version.ref  = "pahoClientVersion"}


[bundles]
coil = ["coil-compose", "coil-network"]
koin = ["koin", "koin-compose"]
retrofit = ["retrofit", "retrofit-converter-moshi", "retrofit-converter-gson", "retrofit-serialization-converter"]
eclipsePahoMQTT = ["paho-client"]


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = {id = "com.google.devtools.ksp", version.ref = "kspPluginVersion"}
gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesVersion"}

